version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
