name: Label Release Branch

on:
  pull_request:
    types: opened

jobs:
  add_automerge_label:
    runs-on: ubuntu-latest
    steps:
      - name: Label
        uses: actions/github-script@v7
        if: github.event.pull_request.author_association == OWNER && ${{ startsWith(github.event.pull_request.title, format('chore(main){0} release', ':')) }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['automerge']
            })
