name: Build
on:
  push:
  pull_request:
    types: [opened, reopened, edited]
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn lint
      - run: yarn build
      - run: yarn test
