name: Release Please
on:
  workflow_run:
    branches: [main]
    workflows: [Build]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
      - uses: actions/github-script@v8
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        env:
          PR: ${{ steps.release.outputs.pr }}
        with:
          script: |
            const ISSUE_NUMBER = JSON.parse(process.env.PR).number
            github.rest.issues.addLabels({
              issue_number: ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['automerge']
            })
