name: Release Please
on:
  workflow_run:
    branches: [main]
    workflows: [Build]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
          pull-request-title-pattern: "release${scope}: ${component} ${version}"
          labels: |
            autorelease: pending
            automerge

