name: Release Please
on:
  workflow_run:
    branches: [main]
    workflows: [Build]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --immutable
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          pull-request-title-pattern: "release${scope}: ${component} ${version}"
          labels: |
            autorelease: pending
            automerge
      - run: yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: yarn npm publish
        if: ${{ steps.release.outputs.release_created }}
