name: Release Please
on:
  workflow_run:
    branches: [main]
    workflows: [Build]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
      - uses: actions/github-script@v7
        if: ${{ steps.release.outputs.prs_created }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: steps.release.outputs.pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['automerge']
            })
